import { createClient } from "@/lib/supabase/server";
import { getSignedDocumentUrls } from "@/lib/documents";
import { PageHeader } from "@/components/page-header";
import { ResumeList } from "@/components/documents/resume-list";

export default async function DocumentsPage() {
  const supabase = await createClient();

  const { data: resumes } = await supabase
    .from("documents")
    .select("*, jobs!documents_job_id_fkey(company_name, position, job_code)")
    .eq("type", "tailored_resume")
    .order("created_at", { ascending: false });

  const resumeList = resumes ?? [];
  const signedUrls = await getSignedDocumentUrls(
    supabase,
    resumeList.map((d) => d.file_url).filter(Boolean) as string[]
  );

  return (
    <div className="flex flex-1 flex-col gap-6">
      <PageHeader
        title="Documents"
        description="Resumes generated by the AI Assistant, saved here for each application."
      />

      <ResumeList documents={resumeList} signedUrls={signedUrls} />
    </div>
  );
}
